### ISSUE TITLE
Unraid

### ISSUE THREAD

**Issue by osnapitsjoey** [imagegenius/docker-ai-chat-app#14]
still not working on unraid. Even tried giving up special permissions. seems like It cant write to a file it cant make if that helps  
`find: /app/immich: No such file or directory
Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
Failed to write image to cache DxXAfpAlrkPLCxzj0zfIeNmMpKSOb7I2M9eiXEvL5kw= [Error: EACCES: permission denied, mkdir '/app/ai-chat-app/.next/cache/images'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/app/ai-chat-app/.next/cache/images'`

is what im getting with or without special perms

**Comment by hydazz** [comment]
oopsie, update the container and lmk how it goes

**Comment by osnapitsjoey** [comment]
Updated. Still a no go. Should I be making a variable that installs sharp?

**Comment by hydazz** [comment]
Sharp is not needed? Can you access the webui?

**Comment by osnapitsjoey** [comment]
Yeah webui is fine! But when I press enter in a chat nothing happens

**Comment by hydazz** [comment]
you can try run `npm install --prefix /app/ai-chat-app sharp` in the container and restart it, but I don't believe this will fix this issue

(--prefix not -p)

**Comment by Explorographer** [comment]
Yeah, also on UNRAID and this docker does nothing.  Can login, add api key, templates, but chat is dead in the water. No response.  Does this docker require a GPU?

**Comment by hydazz** [comment]
any logs?

**Comment by Explorographer** [comment]
Nah, I uninstalled.  I will take a look at it here after the weekend when I get some time.  I will snag some logs and post them when I do.

**Comment by McJoppy** [comment]
There have been a couple of updates for Unraid recently which I installed - and that's when it broke for me.

The obvious thing which looks broken is

```
[next-auth][error][NO_SECRET] 
https://next-auth.js.org/errors#no_secret Please define a `secret` in production. MissingSecret [MissingSecretError]: Please define a `secret` in production.
    at assertConfig (/app/ai-chat-app/node_modules/next-auth/core/lib/assert.js:42:12)
    at AuthHandler (/app/ai-chat-app/node_modules/next-auth/core/index.js:70:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextAuthHandler (/app/ai-chat-app/node_modules/next-auth/next/index.js:24:19)
    at async /app/ai-chat-app/node_modules/next-auth/next/index.js:60:32
    at async Object.apiResolver (/app/ai-chat-app/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async NextNodeServer.runApi (/app/ai-chat-app/node_modules/next/dist/server/next-server.js:514:9)
    at async Object.fn (/app/ai-chat-app/node_modules/next/dist/server/next-server.js:828:35)
    at async Router.execute (/app/ai-chat-app/node_modules/next/dist/server/router.js:243:32)
    at async NextNodeServer.runImpl (/app/ai-chat-app/node_modules/next/dist/server/base-server.js:432:29) {
  code: 'NO_SECRET'
}
```

**Comment by McJoppy** [comment]
If it helps, after upgrade the URI I end up at is `/auth/error?error=Configuration`

**Comment by osnapitsjoey** [comment]
> If it helps, after upgrade the URI I end up at is `/auth/error?error=Configuration`


did you delete the app in reinstall? or add NextURl variables yet? 

ive done that to no avail, but it may help you. seems borked on unraid

**Comment by McJoppy** [comment]
I have only used the Unraid update feature

**Comment by hydazz** [comment]
@McJoppy you are missing some variables, delete the template and reinstall it from CA, or add them manually:
https://github.com/imagegenius/docker-ai-chat-app#variables

I have also added a check for variables... https://github.com/imagegenius/docker-ai-chat-app/commit/a1de736845bef1cc204710ffd4fb5189eba34aa5

**Comment by McJoppy** [comment]
I've reinstalled and filled out the required vars however when trying to re-add the API key it doesn't seem to work:

```
prisma:error 
Invalid `prisma.setting.findMany()` invocation:


The column `main.Setting.userId` does not exist in the current database.

```

**Comment by hydazz** [comment]
delete the appdata

**Comment by McJoppy** [comment]
Sorry - I totally missed the var for `NEXTAUTH_URL` so had the (unaccessible) default.

Updated to IP address for my internal network and can confirm all is good now!

**Comment by osnapitsjoey** [comment]
Damn really? I also have that variable. Have no idea why im getting empty
chats still

**Comment by McJoppy** [comment]
I did also uninstall, delete the appdata dir on the Unraid server before altering the variable.

It's working again for me - try

* Uninstall the app
* Delete eg. `/mnt/cache/appdata/ai-chat-app` or where ever the data is
* Reinstall via app search for `chatgpt`
* _Double check_ vars :)

**Comment by osnapitsjoey** [comment]
Will do!

**Comment by osnapitsjoey** [comment]
> I did also uninstall, delete the appdata dir on the Unraid server before altering the variable.
> 
> It's working again for me - try
> 
> * Uninstall the app
> * Delete eg. `/mnt/cache/appdata/ai-chat-app` or where ever the data is
> * Reinstall via app search for `chatgpt`
> * _Double check_ vars :)

are you ussing the 192.168 ip for your next_URL? ive done all this and stil have the issue

**Comment by hydazz** [comment]
`NEXTAUTH_URL` should be set to `http://<unraid_ip>:3000`

**Comment by McJoppy** [comment]
`NEXTAUTH_URL` seems to be a request sent from your browser and not the Chat AI system ie. if you are accessing the web service via some other URL, this should match that (browser redirects to this URL).

Eg. I use https://chat.some.domain.i.own/ which is reversed proxied via Nginx - so I've set this to https://chat.some.domain.i.own/

**Comment by Explorographer** [comment]
Okay, I re-installed tonight...followed the instructions here and nope...unresponsive chat.  

LOG:

  json: 'true'
} true true
JDDDDDDDIIIIDDD
prisma:error 
Invalid `prisma.chat.findUniqueOrThrow()` invocation:


An operation failed because it depends on one or more records that were required but not found. Expected a record, found none.
prisma:error 
Invalid `prisma.chat.findUniqueOrThrow()` invocation:


An operation failed because it depends on one or more records that were required but not found. Expected a record, found none.
prisma:error 
Invalid `prisma.chat.findUniqueOrThrow()` invocation:


An operation failed because it depends on one or more records that were required but not found. Expected a record, found none.
prisma:error 
Invalid `prisma.chat.findUniqueOrThrow()` invocation:


An operation failed because it depends on one or more records that were required but not found. Expected a record, found none.

**Comment by Explorographer** [comment]
Here is the whole log minus my personal details. 

![image](https://user-images.githubusercontent.com/101281862/228737866-d7ba3e8b-7545-4553-9951-22d386b881a2.png)

**Comment by Explorographer** [comment]
Installed Sharp....same error.   An operation failed because it depends.....

**Comment by hydazz** [comment]
Have you tried deleting the database?

**Comment by Explorographer** [comment]
What database?  I deleted the whole folder out of appdata with the console.

**Comment by hydazz** [comment]
> What database?  I deleted the whole folder out of appdata with the console.  

What's the output of `printenv` in the container?

**Comment by Explorographer** [comment]
It's 3:40am here. Ill get to it in the am.

**Comment by Explorographer** [comment]
Okay, I am back up. What VAR do you need to know?  I am on UNraid btw.

**Comment by McJoppy** [comment]
Once you uninstalled the app, did you remove the app data from the (most likely) cache drive?

On my Unraid system I deleted the folder `/mnt/cache/appdata/ai-chat-app`

**Comment by Explorographer** [comment]
> Once you uninstalled the app, did you remove the app data from the (most likely) cache drive?
> 
> On my Unraid system I deleted the folder `/mnt/cache/appdata/ai-chat-app`

Yes, this is what I always do. Delete the app using the Docker tab, then open a console and wipe it from the appdata folder.  Then go to the app tab and remove the template from the Previously Installed page.  This is a full clean sweep of the app from my system.  I follow up by verifying with Krusader.  Is this not the normal for everyone?  Just the way I have always done it.  And after doing so and re-installing several times...this app/docker does NOT work.  And before any assumptions are made and more advice thrown at me.  I run two 40TB Unraid servers.  Reverse Proxied, Full database and redundant backup, NextCloud, Bitwarden, HomeAssistant servers.  All of this was built (hardware) and software by me.  With that said, I know I still have much to learn.  This year I have actively been doing more things by console than GUI simply for this reason.  I am pretty versed in nGinx and docker installation as well as building VMs.  This app is adapted to UNraid, but not functional.  The answers here have been slightly sketch IMO.   Until this app is verified working, I am not going to install it on my server with an open API key.  Just not a brilliant thing to do.  I can wait 3-6 months to see if this becomes a real thing or not.  In the meantime, I have full access to ChatGPT anyway.  Just thought this might be cool to give my Discord supporters access to.   Good luck!

**Comment by osnapitsjoey** [comment]
Lmfao. Just change some things a bit.

**Comment by Explorographer** [comment]
> 

Not the point.

**Comment by McJoppy** [comment]
I think it's valid to ask what vars have been configured - would be happy to share, to help someone developing a neat open source tool I'm interested in using (FYI the API key is configured via the web interface and not the ENV VARS).

I didn't need to set up anything new - just remove the old install (including deletion of appdata dir) then configure the 4 variables in the Unraid interface
![image](https://user-images.githubusercontent.com/3344098/228951481-e40e4be4-de1c-4167-8734-c37417024e07.png)

**Comment by hydazz** [comment]
> Also, to be clear, when I say sketch, I mean the DEV is asking me to post my VARS here which include my private OpenAI API key, my login and password. I am not going to do that. And that should not be something that is asked of a user on a public forum.

It's not that deep mate, you could have copied and pasted the output of `printenv`, and simply removed any confidential information.
