### ISSUE TITLE
Error when trying to Access the WebUI

### ISSUE THREAD

**Issue by Pwnisher1337** [imagegenius/docker-ai-chat-app#15]
Hello,

I'm using your Chat Bot App on Unraid, i updated it to the new Version and now when i trie to access it, i get an Error on the Page:

![image](https://user-images.githubusercontent.com/41051695/226099571-382c74de-4524-4a4a-a7c9-54f384bcc76b.png)

the URL Points to: auth/error?error=Configuration

If you need any logs or similar, i'm not sure where to look for those.

**Comment by tctitan** [comment]
same after updated

**Comment by insaneFu** [comment]
same after fresh install

**Comment by nomonkeynodeal** [comment]
The log:
[next-auth][error][NO_SECRET] 
https://next-auth.js.org/errors#no_secret
[next-auth][error][NO_SECRET] 
https://next-auth.js.org/errors#no_secret
[next-auth][error][NO_SECRET] 
https://next-auth.js.org/errors#no_secret Please define a `secret` in production. MissingSecret [MissingSecretError]: Please define a `secret` in production.
    at assertConfig (/app/ai-chat-app/node_modules/next-auth/core/lib/assert.js:42:12)
    at AuthHandler (/app/ai-chat-app/node_modules/next-auth/core/index.js:70:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextAuthHandler (/app/ai-chat-app/node_modules/next-auth/next/index.js:24:19)
    at async /app/ai-chat-app/node_modules/next-auth/next/index.js:60:32
    at async Object.apiResolver (/app/ai-chat-app/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async NextNodeServer.runApi (/app/ai-chat-app/node_modules/next/dist/server/next-server.js:514:9)
    at async Object.fn (/app/ai-chat-app/node_modules/next/dist/server/next-server.js:828:35)
    at async Router.execute (/app/ai-chat-app/node_modules/next/dist/server/router.js:243:32)
    at async NextNodeServer.runImpl (/app/ai-chat-app/node_modules/next/dist/server/base-server.js:432:29) {
  code: 'NO_SECRET'
}

**Comment by hydazz** [comment]
This is caused by the new multi-user support, https://github.com/bitswired/ai-chat-app/commit/ea92abd6d2ce462b1511fb5f1012d4f136ece589

Edit the template and add the following variables, I will add these into the template soon:
<img width="1512" alt="Screenshot 2023-03-19 at 5 29 31 pm" src="https://user-images.githubusercontent.com/53986978/226158225-25ffdd1a-da3f-4570-aa14-dd2108ae2d4a.png">

`NEXTAUTH_SECRET=secret`, I have no idea what this does, but probably set it to a random string
`NEXTAUTH_URL=http://192.168.1.2:3000` set this to the IP address you use to access the container (and the port)
`ADMIN_EMAIL=email@me.com` email used on the login screen
`ADMIN_PASSWORD=password` password used on the login screen

**Comment by hydazz** [comment]
https://github.com/imagegenius/docker-ai-chat-app/commit/8126326b5614eb8d3e960790c655ddb757146cee
